export { dedupeLibraryRecords, upsertMoviesLibrary } from './libraryDedupe.js';
export { supabase } from './supabaseClient.js';
export { default } from './supabaseClient.js';

export {
    getCurrentUser,
    getSession,
    getUserProfile,
    isProfileOnboarded,
    checkUsernameAvailable,
    updateUserProfile,
    getUserTasteProfile,
    ensureUserProfile,
} from './db/profiles.js';

export {
    getMovieReviews,
    getMovieRatings,
    getBatchMovieRatings,
    getUserRatingForMovie,
    submitRating,
    getAllUserRatings,
    submitReview,
    upvoteReview,
    removeUpvoteReview,
} from './db/ratings.js';

export {
    getMoviesLibrary,
    getMoviesByCollection,
    getMoviesByDisplaySection,
    getMovieFromLibrary,
    saveMovieToLibrary,
    bulkSaveMoviesToLibrary,
    updateMovieInLibrary,
    deleteMovieFromLibrary,
    toggleMovieFeatured,
    toggleMovieActive,
    updateMovieCollections,
    updateMovieDisplaySections,
    updateMovieStreamingPlatforms,
    updateMovieVibes,
    updateMovieParentGuide,
    updateMovieEditorReview,
    searchMoviesLibrary,
    getLibraryStats,
    getMoviesFromLibraryByIds,
    saveFullMovieToLibrary,
    getAdvancedMovieFromLibrary,
    getAdvancedLibraryStats,
    getAdvancedMoviesLibrary,
    searchAdvancedMoviesLibrary,
    checkMovieInAdvancedLibrary,
    checkMoviesInAdvancedLibrary,
} from './db/library.js';

export {
    getHomepageSections,
    createHomepageSection,
    updateHomepageSection,
    deleteHomepageSection,
    getTVSections,
    toggleHomepageSectionActive,
    reorderHomepageSections,
    getShowcaseTrailers,
    createShowcaseTrailer,
    updateShowcaseTrailer,
    deleteShowcaseTrailer,
    toggleShowcaseTrailerActive,
    reorderShowcaseTrailers,
    addMovieToSection,
    removeMovieFromSection,
    reorderSectionMovies,
} from './db/sections.js';

export {
    getRssSources,
    createRssSource,
    RSS_FILTER_DEFAULTS,
    getRssGlobalFilters,
    setRssGlobalFilters,
    updateRssSource,
    toggleRssSourceActive,
    deleteRssSource,
    getFeedArticles,
    getFeedArticleCountsBySource,
    updateFeedArticleStatus,
    toggleFeedArticleActive,
    deleteFeedArticle,
} from './db/rss.js';

export {
    getUserMovieStatus,
    toggleWatchlist,
    toggleLikedMovie,
    toggleWatchedMovie,
    getUserWatchlist,
    getUserLikedMovies,
    getUserWatchedMovies,
} from './db/userLists.js';

export {
    getCollections,
    createCollection,
    updateCollectionAdmin,
    deleteCollection,
    updateCollection,
    LIST_NAME_MAX,
    LIST_DESCRIPTION_MAX,
    getUserCollections,
    createUserCollection,
    getCollectionBySlug,
    updateUserCollection,
    addToCollection,
    removeFromCollection,
    getCollection,
    getCollectionByName,
    addMoviesToCollection,
    deleteUserCollection,
} from './db/collections.js';

export {
    BOARD_TITLE_MAX,
    BOARD_DESCRIPTION_MAX,
    BOARD_NOTE_MAX,
    createBoardSlug,
    boardPath,
    getUserBoards,
    createBoard,
    getBoardBySlug,
    updateBoard,
    deleteBoard,
    addBoardItem,
    addBoardItems,
    removeBoardItem,
    updateBoardItem,
    reorderBoardItems,
    incrementBoardViews,
    toggleBoardLike,
    isBoardLiked,
    getBoardComments,
    addBoardComment,
    deleteBoardComment,
    exploreBoards,
    searchPublicBoards,
    getFollowedBoardActivity,
    itemHref,
    itemImageUrl,
    stillItemId,
} from './db/boards.js';

export {
    toggleFollow,
    getUserFollowers,
    getUserFollowing,
    isFollowing,
    searchProfiles,
    searchPublicCollections,
    getProfileByUsername,
    getUserRatingsCount,
} from './db/social.js';

export {
    getGlobalUserStats,
    DEFAULT_APP_SETTINGS,
    getAppSettings,
    saveAppSettings,
    getSyncState,
    getTvSeasonsBackfillRemaining,
    getSyncRuns,
    getContentEvents,
    createContentEvent,
    updateContentEventStatus,
} from './db/adminOps.js';
