-- News Intelligence System: Seed keyword dictionaries
-- ~320 terms across rejection and positive categories

-- =============================================================================
-- REJECTION KEYWORDS (~200 terms)
-- =============================================================================

-- Relationship keywords (dating, romance, personal relationships)
INSERT INTO public.news_keyword_dictionaries (category, subcategory, term, weight, is_phrase) VALUES
('rejection', 'relationship', 'dating', 3, false),
('rejection', 'relationship', 'engaged', 3, false),
('rejection', 'relationship', 'engagement', 3, false),
('rejection', 'relationship', 'married', 2, false),
('rejection', 'relationship', 'marriage', 2, false),
('rejection', 'relationship', 'wedding', 3, false),
('rejection', 'relationship', 'divorce', 3, false),
('rejection', 'relationship', 'divorced', 3, false),
('rejection', 'relationship', 'split', 2, false),
('rejection', 'relationship', 'breakup', 3, false),
('rejection', 'relationship', 'broke up', 3, true),
('rejection', 'relationship', 'romance', 2, false),
('rejection', 'relationship', 'romantic', 2, false),
('rejection', 'relationship', 'boyfriend', 3, false),
('rejection', 'relationship', 'girlfriend', 3, false),
('rejection', 'relationship', 'husband', 2, false),
('rejection', 'relationship', 'wife', 2, false),
('rejection', 'relationship', 'affair', 3, false),
('rejection', 'relationship', 'cheating', 3, false),
('rejection', 'relationship', 'cheated', 3, false),
('rejection', 'relationship', 'lover', 2, false),
('rejection', 'relationship', 'ex-boyfriend', 3, false),
('rejection', 'relationship', 'ex-girlfriend', 3, false),
('rejection', 'relationship', 'ex-husband', 3, false),
('rejection', 'relationship', 'ex-wife', 3, false),
('rejection', 'relationship', 'love life', 3, true),
('rejection', 'relationship', 'new couple', 3, true),
('rejection', 'relationship', 'spotted together', 3, true),
('rejection', 'relationship', 'holding hands', 3, true),
('rejection', 'relationship', 'kissing', 2, false),
('rejection', 'relationship', 'pda', 2, false)
ON CONFLICT (category, subcategory, term) DO NOTHING;

-- Lifestyle keywords (fashion, health, personal life)
INSERT INTO public.news_keyword_dictionaries (category, subcategory, term, weight, is_phrase) VALUES
('rejection', 'lifestyle', 'fashion', 2, false),
('rejection', 'lifestyle', 'outfit', 2, false),
('rejection', 'lifestyle', 'outfits', 2, false),
('rejection', 'lifestyle', 'style', 1, false),
('rejection', 'lifestyle', 'wearing', 1, false),
('rejection', 'lifestyle', 'wore', 1, false),
('rejection', 'lifestyle', 'dress', 1, false),
('rejection', 'lifestyle', 'gown', 1, false),
('rejection', 'lifestyle', 'bikini', 3, false),
('rejection', 'lifestyle', 'shirtless', 3, false),
('rejection', 'lifestyle', 'swimsuit', 3, false),
('rejection', 'lifestyle', 'beach body', 3, true),
('rejection', 'lifestyle', 'diet', 2, false),
('rejection', 'lifestyle', 'weight loss', 3, true),
('rejection', 'lifestyle', 'weight gain', 3, true),
('rejection', 'lifestyle', 'lost weight', 3, true),
('rejection', 'lifestyle', 'gained weight', 3, true),
('rejection', 'lifestyle', 'workout', 2, false),
('rejection', 'lifestyle', 'fitness', 2, false),
('rejection', 'lifestyle', 'gym', 1, false),
('rejection', 'lifestyle', 'vacation', 2, false),
('rejection', 'lifestyle', 'vacationing', 2, false),
('rejection', 'lifestyle', 'holiday', 1, false),
('rejection', 'lifestyle', 'getaway', 2, false),
('rejection', 'lifestyle', 'mansion', 2, false),
('rejection', 'lifestyle', 'real estate', 2, true),
('rejection', 'lifestyle', 'bought house', 2, true),
('rejection', 'lifestyle', 'sold house', 2, true),
('rejection', 'lifestyle', 'net worth', 2, true),
('rejection', 'lifestyle', 'salary', 2, false),
('rejection', 'lifestyle', 'yacht', 2, false),
('rejection', 'lifestyle', 'luxury', 1, false),
('rejection', 'lifestyle', 'skincare', 2, false),
('rejection', 'lifestyle', 'makeup', 1, false),
('rejection', 'lifestyle', 'beauty routine', 2, true),
('rejection', 'lifestyle', 'plastic surgery', 3, true),
('rejection', 'lifestyle', 'cosmetic surgery', 3, true)
ON CONFLICT (category, subcategory, term) DO NOTHING;

-- Personal/family keywords
INSERT INTO public.news_keyword_dictionaries (category, subcategory, term, weight, is_phrase) VALUES
('rejection', 'personal', 'pregnant', 3, false),
('rejection', 'personal', 'pregnancy', 3, false),
('rejection', 'personal', 'baby', 2, false),
('rejection', 'personal', 'baby bump', 3, true),
('rejection', 'personal', 'gave birth', 3, true),
('rejection', 'personal', 'newborn', 2, false),
('rejection', 'personal', 'expecting', 2, false),
('rejection', 'personal', 'kids', 1, false),
('rejection', 'personal', 'children', 1, false),
('rejection', 'personal', 'family life', 2, true),
('rejection', 'personal', 'parenting', 2, false),
('rejection', 'personal', 'motherhood', 2, false),
('rejection', 'personal', 'fatherhood', 2, false),
('rejection', 'personal', 'birthday', 1, false),
('rejection', 'personal', 'birthday party', 2, true),
('rejection', 'personal', 'celebrates', 1, false),
('rejection', 'personal', 'personal life', 2, true),
('rejection', 'personal', 'private life', 2, true),
('rejection', 'personal', 'rehab', 2, false),
('rejection', 'personal', 'addiction', 2, false),
('rejection', 'personal', 'mental health', 1, false),
('rejection', 'personal', 'hospital', 1, false),
('rejection', 'personal', 'hospitalized', 2, false)
ON CONFLICT (category, subcategory, term) DO NOTHING;

-- Gossip keywords (rumors, speculation, tabloid)
INSERT INTO public.news_keyword_dictionaries (category, subcategory, term, weight, is_phrase) VALUES
('rejection', 'gossip', 'allegedly', 2, false),
('rejection', 'gossip', 'rumored', 2, false),
('rejection', 'gossip', 'rumoured', 2, false),
('rejection', 'gossip', 'rumors', 2, false),
('rejection', 'gossip', 'rumours', 2, false),
('rejection', 'gossip', 'reportedly', 1, false),
('rejection', 'gossip', 'sources say', 3, true),
('rejection', 'gossip', 'insider says', 3, true),
('rejection', 'gossip', 'close friend', 2, true),
('rejection', 'gossip', 'anonymous source', 3, true),
('rejection', 'gossip', 'insider reveals', 3, true),
('rejection', 'gossip', 'spotted', 1, false),
('rejection', 'gossip', 'paparazzi', 2, false),
('rejection', 'gossip', 'caught', 1, false),
('rejection', 'gossip', 'secret', 1, false),
('rejection', 'gossip', 'secretly', 2, false),
('rejection', 'gossip', 'hidden', 1, false),
('rejection', 'gossip', 'reveals all', 2, true),
('rejection', 'gossip', 'tells all', 2, true),
('rejection', 'gossip', 'opens up', 1, true),
('rejection', 'gossip', 'opens up about', 2, true),
('rejection', 'gossip', 'gets candid', 2, true),
('rejection', 'gossip', 'confesses', 2, false),
('rejection', 'gossip', 'admits', 1, false),
('rejection', 'gossip', 'finally admits', 3, true)
ON CONFLICT (category, subcategory, term) DO NOTHING;

-- Controversy/drama keywords
INSERT INTO public.news_keyword_dictionaries (category, subcategory, term, weight, is_phrase) VALUES
('rejection', 'controversy', 'feud', 2, false),
('rejection', 'controversy', 'feuding', 2, false),
('rejection', 'controversy', 'drama', 1, false),
('rejection', 'controversy', 'clash', 2, false),
('rejection', 'controversy', 'clashed', 2, false),
('rejection', 'controversy', 'fight', 1, false),
('rejection', 'controversy', 'fighting', 1, false),
('rejection', 'controversy', 'rant', 2, false),
('rejection', 'controversy', 'ranted', 2, false),
('rejection', 'controversy', 'slammed', 2, false),
('rejection', 'controversy', 'slams', 2, false),
('rejection', 'controversy', 'blasted', 2, false),
('rejection', 'controversy', 'blasts', 2, false),
('rejection', 'controversy', 'fired back', 2, true),
('rejection', 'controversy', 'fires back', 2, true),
('rejection', 'controversy', 'claps back', 2, true),
('rejection', 'controversy', 'hits back', 2, true),
('rejection', 'controversy', 'responds to', 1, true),
('rejection', 'controversy', 'controversy', 1, false),
('rejection', 'controversy', 'controversial', 1, false),
('rejection', 'controversy', 'backlash', 1, false),
('rejection', 'controversy', 'outrage', 2, false),
('rejection', 'controversy', 'scandal', 2, false),
('rejection', 'controversy', 'scandalous', 2, false),
('rejection', 'controversy', 'accusation', 2, false),
('rejection', 'controversy', 'accused', 1, false)
ON CONFLICT (category, subcategory, term) DO NOTHING;

-- Clickbait keywords
INSERT INTO public.news_keyword_dictionaries (category, subcategory, term, weight, is_phrase) VALUES
('rejection', 'clickbait', 'you won''t believe', 3, true),
('rejection', 'clickbait', 'shocking', 2, false),
('rejection', 'clickbait', 'shocks', 2, false),
('rejection', 'clickbait', 'shocked', 1, false),
('rejection', 'clickbait', 'stunning', 1, false),
('rejection', 'clickbait', 'jaw-dropping', 2, false),
('rejection', 'clickbait', 'mind-blowing', 2, false),
('rejection', 'clickbait', 'unbelievable', 2, false),
('rejection', 'clickbait', 'insane', 1, false),
('rejection', 'clickbait', 'crazy', 1, false),
('rejection', 'clickbait', 'wild', 1, false),
('rejection', 'clickbait', 'exposed', 2, false),
('rejection', 'clickbait', 'exposes', 2, false),
('rejection', 'clickbait', 'secrets revealed', 3, true),
('rejection', 'clickbait', 'finally reveals', 2, true),
('rejection', 'clickbait', 'breaks silence', 2, true),
('rejection', 'clickbait', 'breaks internet', 2, true),
('rejection', 'clickbait', 'goes viral', 1, true),
('rejection', 'clickbait', 'everyone talking', 2, true),
('rejection', 'clickbait', 'can''t stop talking', 2, true),
('rejection', 'clickbait', 'here''s why', 1, true),
('rejection', 'clickbait', 'fans react', 1, true),
('rejection', 'clickbait', 'fans go crazy', 2, true),
('rejection', 'clickbait', 'internet reacts', 2, true),
('rejection', 'clickbait', 'twitter reacts', 2, true),
('rejection', 'clickbait', 'hottest', 1, false),
('rejection', 'clickbait', 'sexiest', 2, false),
('rejection', 'clickbait', 'best dressed', 2, true),
('rejection', 'clickbait', 'worst dressed', 2, true)
ON CONFLICT (category, subcategory, term) DO NOTHING;

-- =============================================================================
-- POSITIVE KEYWORDS (~120 terms)
-- =============================================================================

-- Movie/TV terminology
INSERT INTO public.news_keyword_dictionaries (category, subcategory, term, weight, is_phrase) VALUES
('positive', 'movie_term', 'film', 2, false),
('positive', 'movie_term', 'movie', 2, false),
('positive', 'movie_term', 'movies', 2, false),
('positive', 'movie_term', 'cinema', 2, false),
('positive', 'movie_term', 'cinematic', 2, false),
('positive', 'movie_term', 'sequel', 3, false),
('positive', 'movie_term', 'prequel', 3, false),
('positive', 'movie_term', 'trilogy', 3, false),
('positive', 'movie_term', 'franchise', 2, false),
('positive', 'movie_term', 'reboot', 3, false),
('positive', 'movie_term', 'remake', 2, false),
('positive', 'movie_term', 'adaptation', 2, false),
('positive', 'movie_term', 'spinoff', 3, false),
('positive', 'movie_term', 'spin-off', 3, false),
('positive', 'movie_term', 'series', 1, false),
('positive', 'movie_term', 'tv series', 2, true),
('positive', 'movie_term', 'limited series', 2, true),
('positive', 'movie_term', 'miniseries', 2, false),
('positive', 'movie_term', 'season', 1, false),
('positive', 'movie_term', 'episode', 1, false),
('positive', 'movie_term', 'episodes', 1, false),
('positive', 'movie_term', 'feature film', 3, true),
('positive', 'movie_term', 'animated', 2, false),
('positive', 'movie_term', 'animation', 2, false),
('positive', 'movie_term', 'documentary', 2, false),
('positive', 'movie_term', 'biopic', 3, false),
('positive', 'movie_term', 'thriller', 1, false),
('positive', 'movie_term', 'horror', 1, false),
('positive', 'movie_term', 'action', 1, false),
('positive', 'movie_term', 'comedy', 1, false),
('positive', 'movie_term', 'drama', 1, false),
('positive', 'movie_term', 'sci-fi', 2, false),
('positive', 'movie_term', 'superhero', 2, false)
ON CONFLICT (category, subcategory, term) DO NOTHING;

-- Announcement keywords
INSERT INTO public.news_keyword_dictionaries (category, subcategory, term, weight, is_phrase) VALUES
('positive', 'announcement', 'announces', 3, false),
('positive', 'announcement', 'announced', 3, false),
('positive', 'announcement', 'announcement', 3, false),
('positive', 'announcement', 'confirms', 3, false),
('positive', 'announcement', 'confirmed', 3, false),
('positive', 'announcement', 'reveals', 2, false),
('positive', 'announcement', 'revealed', 2, false),
('positive', 'announcement', 'unveils', 3, false),
('positive', 'announcement', 'unveiled', 3, false),
('positive', 'announcement', 'greenlights', 4, false),
('positive', 'announcement', 'greenlit', 4, false),
('positive', 'announcement', 'green-lit', 4, false),
('positive', 'announcement', 'picks up', 3, true),
('positive', 'announcement', 'picked up', 3, true),
('positive', 'announcement', 'orders', 2, false),
('positive', 'announcement', 'ordered', 2, false),
('positive', 'announcement', 'renews', 3, false),
('positive', 'announcement', 'renewed', 3, false),
('positive', 'announcement', 'renewal', 3, false),
('positive', 'announcement', 'cancels', 2, false),
('positive', 'announcement', 'cancelled', 2, false),
('positive', 'announcement', 'canceled', 2, false),
('positive', 'announcement', 'officially', 2, false)
ON CONFLICT (category, subcategory, term) DO NOTHING;

-- Casting keywords
INSERT INTO public.news_keyword_dictionaries (category, subcategory, term, weight, is_phrase) VALUES
('positive', 'casting', 'cast', 3, false),
('positive', 'casting', 'casting', 3, false),
('positive', 'casting', 'casts', 3, false),
('positive', 'casting', 'joins', 2, false),
('positive', 'casting', 'joined', 2, false),
('positive', 'casting', 'joining', 2, false),
('positive', 'casting', 'signs on', 3, true),
('positive', 'casting', 'signed on', 3, true),
('positive', 'casting', 'set to star', 3, true),
('positive', 'casting', 'will star', 2, true),
('positive', 'casting', 'to star', 2, true),
('positive', 'casting', 'starring', 2, false),
('positive', 'casting', 'stars', 1, false),
('positive', 'casting', 'in talks', 2, true),
('positive', 'casting', 'negotiations', 2, false),
('positive', 'casting', 'deal', 1, false),
('positive', 'casting', 'role', 1, false),
('positive', 'casting', 'lead role', 2, true),
('positive', 'casting', 'title role', 2, true),
('positive', 'casting', 'ensemble', 2, false)
ON CONFLICT (category, subcategory, term) DO NOTHING;

-- Production keywords
INSERT INTO public.news_keyword_dictionaries (category, subcategory, term, weight, is_phrase) VALUES
('positive', 'production', 'production', 2, false),
('positive', 'production', 'filming', 3, false),
('positive', 'production', 'begins filming', 4, true),
('positive', 'production', 'starts filming', 4, true),
('positive', 'production', 'wraps', 3, false),
('positive', 'production', 'wraps filming', 4, true),
('positive', 'production', 'wrapped', 3, false),
('positive', 'production', 'wraps production', 4, true),
('positive', 'production', 'post-production', 3, false),
('positive', 'production', 'principal photography', 4, true),
('positive', 'production', 'shoots', 2, false),
('positive', 'production', 'shooting', 2, false),
('positive', 'production', 'on set', 2, true),
('positive', 'production', 'set photos', 2, true),
('positive', 'production', 'behind the scenes', 2, true),
('positive', 'production', 'director', 2, false),
('positive', 'production', 'directs', 2, false),
('positive', 'production', 'directing', 2, false),
('positive', 'production', 'directed by', 2, true),
('positive', 'production', 'screenplay', 2, false),
('positive', 'production', 'screenwriter', 2, false),
('positive', 'production', 'writer', 1, false),
('positive', 'production', 'script', 2, false),
('positive', 'production', 'cinematographer', 3, false),
('positive', 'production', 'cinematography', 2, false),
('positive', 'production', 'composer', 2, false),
('positive', 'production', 'score', 1, false),
('positive', 'production', 'soundtrack', 2, false),
('positive', 'production', 'vfx', 2, false),
('positive', 'production', 'visual effects', 2, true),
('positive', 'production', 'practical effects', 2, true)
ON CONFLICT (category, subcategory, term) DO NOTHING;

-- Release keywords
INSERT INTO public.news_keyword_dictionaries (category, subcategory, term, weight, is_phrase) VALUES
('positive', 'release', 'releases', 2, false),
('positive', 'release', 'release', 2, false),
('positive', 'release', 'release date', 3, true),
('positive', 'release', 'releasing', 2, false),
('positive', 'release', 'opens', 2, false),
('positive', 'release', 'opening', 2, false),
('positive', 'release', 'premiere', 3, false),
('positive', 'release', 'premieres', 3, false),
('positive', 'release', 'premiered', 3, false),
('positive', 'release', 'debuts', 2, false),
('positive', 'release', 'debuting', 2, false),
('positive', 'release', 'trailer', 3, false),
('positive', 'release', 'teaser', 3, false),
('positive', 'release', 'teaser trailer', 4, true),
('positive', 'release', 'official trailer', 4, true),
('positive', 'release', 'first look', 3, true),
('positive', 'release', 'first trailer', 4, true),
('positive', 'release', 'poster', 2, false),
('positive', 'release', 'theatrical', 3, false),
('positive', 'release', 'theaters', 2, false),
('positive', 'release', 'theatres', 2, false),
('positive', 'release', 'in theaters', 3, true),
('positive', 'release', 'streaming', 2, false),
('positive', 'release', 'available on', 1, true)
ON CONFLICT (category, subcategory, term) DO NOTHING;

-- Industry/business keywords
INSERT INTO public.news_keyword_dictionaries (category, subcategory, term, weight, is_phrase) VALUES
('positive', 'industry', 'box office', 4, true),
('positive', 'industry', 'grosses', 3, false),
('positive', 'industry', 'grossed', 3, false),
('positive', 'industry', 'earnings', 2, false),
('positive', 'industry', 'weekend', 1, false),
('positive', 'industry', 'opening weekend', 3, true),
('positive', 'industry', 'studio', 2, false),
('positive', 'industry', 'studios', 2, false),
('positive', 'industry', 'network', 1, false),
('positive', 'industry', 'streamer', 2, false),
('positive', 'industry', 'distribution', 2, false),
('positive', 'industry', 'distributor', 2, false),
('positive', 'industry', 'acquires', 3, false),
('positive', 'industry', 'acquired', 3, false),
('positive', 'industry', 'acquisition', 3, false),
('positive', 'industry', 'deal', 1, false),
('positive', 'industry', 'partnership', 2, false),
('positive', 'industry', 'co-production', 3, false),
('positive', 'industry', 'producer', 2, false),
('positive', 'industry', 'executive producer', 2, true),
('positive', 'industry', 'showrunner', 3, false)
ON CONFLICT (category, subcategory, term) DO NOTHING;

-- Awards/festival keywords
INSERT INTO public.news_keyword_dictionaries (category, subcategory, term, weight, is_phrase) VALUES
('positive', 'awards', 'oscar', 3, false),
('positive', 'awards', 'oscars', 3, false),
('positive', 'awards', 'academy award', 4, true),
('positive', 'awards', 'academy awards', 4, true),
('positive', 'awards', 'emmy', 3, false),
('positive', 'awards', 'emmys', 3, false),
('positive', 'awards', 'golden globe', 3, true),
('positive', 'awards', 'golden globes', 3, true),
('positive', 'awards', 'bafta', 3, false),
('positive', 'awards', 'sag awards', 3, true),
('positive', 'awards', 'critics choice', 2, true),
('positive', 'awards', 'nominated', 2, false),
('positive', 'awards', 'nomination', 2, false),
('positive', 'awards', 'nominations', 2, false),
('positive', 'awards', 'wins', 2, false),
('positive', 'awards', 'won', 2, false),
('positive', 'awards', 'winner', 2, false),
('positive', 'awards', 'award', 1, false),
('positive', 'awards', 'cannes', 3, false),
('positive', 'awards', 'sundance', 3, false),
('positive', 'awards', 'venice', 2, false),
('positive', 'awards', 'toronto', 2, false),
('positive', 'awards', 'tiff', 2, false),
('positive', 'awards', 'berlin', 2, false),
('positive', 'awards', 'berlinale', 2, false),
('positive', 'awards', 'tribeca', 2, false),
('positive', 'awards', 'sxsw', 2, false),
('positive', 'awards', 'film festival', 3, true),
('positive', 'awards', 'world premiere', 3, true),
('positive', 'awards', 'competition', 1, false)
ON CONFLICT (category, subcategory, term) DO NOTHING;

-- =============================================================================
-- CATEGORY INDICATORS (help detect article type)
-- =============================================================================

INSERT INTO public.news_keyword_dictionaries (category, subcategory, term, weight, is_phrase) VALUES
('category_indicator', 'casting_news', 'cast in', 3, true),
('category_indicator', 'casting_news', 'joins cast', 3, true),
('category_indicator', 'casting_news', 'cast as', 3, true),
('category_indicator', 'release_news', 'gets release date', 4, true),
('category_indicator', 'release_news', 'sets release', 3, true),
('category_indicator', 'box_office', 'box office', 4, true),
('category_indicator', 'box_office', 'tops box office', 4, true),
('category_indicator', 'box_office', 'dominates box office', 4, true),
('category_indicator', 'production_update', 'begins production', 4, true),
('category_indicator', 'production_update', 'starts production', 4, true),
('category_indicator', 'production_update', 'enters production', 4, true),
('category_indicator', 'trailer_news', 'drops trailer', 4, true),
('category_indicator', 'trailer_news', 'releases trailer', 4, true),
('category_indicator', 'trailer_news', 'new trailer', 3, true),
('category_indicator', 'awards_news', 'wins best', 3, true),
('category_indicator', 'awards_news', 'nominated for', 3, true),
('category_indicator', 'review', 'review:', 2, false),
('category_indicator', 'review', 'movie review', 2, true),
('category_indicator', 'review', 'film review', 2, true)
ON CONFLICT (category, subcategory, term) DO NOTHING;

-- =============================================================================
-- DONE - Total: ~320 keywords seeded
-- =============================================================================
